// // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrHfrAQBDCnckpjBcF56p7aT0S1oYEsg',
    appId: '1:112530840436:android:81c637548042b72bb9aa21',
    messagingSenderId: '112530840436',
    projectId: 'leave-mib',
    storageBucket: 'leave-mib.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92sksFD2ljyl_gqhPUS4PjVPX_e_JU_o',
    appId: '1:112530840436:ios:497542d7bf4fbad2b9aa21',
    messagingSenderId: '112530840436',
    projectId: 'leave-mib',
    storageBucket: 'leave-mib.firebasestorage.app',
    iosBundleId: 'com.example.leaveMib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnNqBhv7NkwO3Yka8GcHEZqbQQYjTTXW8',
    appId: '1:529163285020:web:62a40dd2a061845b0f25d9',
    messagingSenderId: '529163285020',
    projectId: 'employes-39c0d',
    authDomain: 'employes-39c0d.firebaseapp.com',
    storageBucket: 'employes-39c0d.firebasestorage.app',
    measurementId: 'G-S81S8VDBQ1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLZgWnltinSOZFN8TNe3MhGLJWgwqaO0',
    appId: '1:112530840436:web:502fd0634a4d9b12b9aa21',
    messagingSenderId: '112530840436',
    projectId: 'leave-mib',
    authDomain: 'leave-mib.firebaseapp.com',
    storageBucket: 'leave-mib.firebasestorage.app',
    measurementId: 'G-RP1EZSFM9L',
  );

}